-- ============================================================
-- SNOWCONE WAREHOUSE — Database, Schema, Tables Setup
-- Run this as ACCOUNTADMIN in your Snowflake console
-- ============================================================

USE ROLE ACCOUNTADMIN;

-- ── Database & Schema ──────────────────────────────────────
CREATE DATABASE IF NOT EXISTS SNOWCONE_DB;
USE DATABASE SNOWCONE_DB;
CREATE SCHEMA IF NOT EXISTS SNOWCONE;
USE SCHEMA SNOWCONE;

-- ── Warehouse (use existing or create) ─────────────────────
CREATE WAREHOUSE IF NOT EXISTS SNOWCONE_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

-- ── Tables ─────────────────────────────────────────────────

CREATE OR REPLACE TABLE LOCATIONS (
    LOCATION_ID     INT PRIMARY KEY,
    NAME            VARCHAR(100) NOT NULL,
    CITY            VARCHAR(100) NOT NULL,
    STATE           VARCHAR(2) NOT NULL,
    ADDRESS         VARCHAR(200),
    MANAGER_NAME    VARCHAR(100),
    OPEN_DATE       DATE,
    SEATING_CAPACITY INT,
    IS_ACTIVE       BOOLEAN DEFAULT TRUE
);

CREATE OR REPLACE TABLE DAILY_SALES (
    SALE_ID         INT AUTOINCREMENT PRIMARY KEY,
    LOCATION_ID     INT NOT NULL REFERENCES LOCATIONS(LOCATION_ID),
    SALE_DATE       DATE NOT NULL,
    ORDER_TYPE      VARCHAR(20) NOT NULL,  -- 'dine-in', 'takeout', 'delivery'
    REVENUE         DECIMAL(10,2) NOT NULL,
    NUM_ORDERS      INT NOT NULL,
    AVG_ORDER_VALUE DECIMAL(8,2) NOT NULL
);

CREATE OR REPLACE TABLE CUSTOMER_REVIEWS (
    REVIEW_ID       INT AUTOINCREMENT PRIMARY KEY,
    LOCATION_ID     INT NOT NULL REFERENCES LOCATIONS(LOCATION_ID),
    REVIEW_DATE     DATE NOT NULL,
    RATING          DECIMAL(2,1) NOT NULL,  -- 1.0 to 5.0
    REVIEW_TEXT     VARCHAR(500),
    CUSTOMER_NAME   VARCHAR(100)
);

CREATE OR REPLACE TABLE INVENTORY (
    INVENTORY_ID    INT AUTOINCREMENT PRIMARY KEY,
    LOCATION_ID     INT NOT NULL REFERENCES LOCATIONS(LOCATION_ID),
    RECORD_DATE     DATE NOT NULL,
    CATEGORY        VARCHAR(50) NOT NULL,  -- 'dairy', 'produce', 'cones_cups', 'toppings', 'syrups'
    UNITS_RECEIVED  INT NOT NULL,
    UNITS_USED      INT NOT NULL,
    UNITS_WASTED    INT NOT NULL,
    WASTE_COST      DECIMAL(8,2) NOT NULL
);

-- ── Read-only role & user for interns ──────────────────────

CREATE ROLE IF NOT EXISTS SNOWCONE_READONLY;

GRANT USAGE ON DATABASE SNOWCONE_DB TO ROLE SNOWCONE_READONLY;
GRANT USAGE ON SCHEMA SNOWCONE_DB.SNOWCONE TO ROLE SNOWCONE_READONLY;
GRANT SELECT ON ALL TABLES IN SCHEMA SNOWCONE_DB.SNOWCONE TO ROLE SNOWCONE_READONLY;
GRANT SELECT ON FUTURE TABLES IN SCHEMA SNOWCONE_DB.SNOWCONE TO ROLE SNOWCONE_READONLY;
GRANT USAGE ON WAREHOUSE SNOWCONE_WH TO ROLE SNOWCONE_READONLY;

CREATE USER IF NOT EXISTS SNOWCONE_USER
  PASSWORD = 'Snowcone2026!'
  DEFAULT_ROLE = SNOWCONE_READONLY
  DEFAULT_WAREHOUSE = SNOWCONE_WH
  DEFAULT_NAMESPACE = SNOWCONE_DB.SNOWCONE
  MUST_CHANGE_PASSWORD = FALSE;

GRANT ROLE SNOWCONE_READONLY TO USER SNOWCONE_USER;

-- ============================================================
-- Done! Now run 02_seed_data.sql to populate with mock data.
-- ============================================================
